//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitirmeProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalsVaccinations
    {
        public long Id { get; set; }
        public string VaccineName { get; set; }
        public Nullable<System.DateTime> VaccinationDate { get; set; }
        public Nullable<System.DateTime> RecurrenceDate { get; set; }
        public Nullable<long> AnimalId { get; set; }
    
        public virtual Animals Animals { get; set; }
    }
}
