//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitirmeProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> VetId { get; set; }
        public Nullable<decimal> RatingScore { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual VetUsers VetUsers { get; set; }
    }
}
