//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitirmeProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Questions()
        {
            this.FromUserToVetMessages = new HashSet<FromUserToVetMessages>();
        }
    
        public long Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> VetId { get; set; }
        public Nullable<int> RatingScore { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual VetUsers VetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FromUserToVetMessages> FromUserToVetMessages { get; set; }
    }
}
